### ISSUE TITLE
Thoughts on reorganizing BEIR main landing page

### ISSUE THREAD

**Issue by lintool** [beir-cellar/beir#94]
tl;dr - IMO the current README landing page tries to do too much... I think we should trim down.

For example, why do we have these?
- https://github.com/beir-cellar/beir#beers-course-material-on-ir
- https://github.com/beir-cellar/beir#beers-multilingual-datasets 

People come to the page for the dataset itself? So these should come first:
- https://github.com/beir-cellar/beir#beers-quick-example
- https://github.com/beir-cellar/beir#beers-available-datasets

All the examples and baselines should come later?

Thoughts @NThakur20 ?

**Comment by NThakur20** [comment]
Hi @lintool, 

Sounds good to me. I think we can reposition the quick example and available datasets on top and push course material and multilingual datasets further down on the landing page. 

I kept the course material on the IR page, in case someone is not familiar with retrieval or dense retrieval, they can refer to these course materials available online. Similarly, BEIR can also support the evaluation of multilingual datasets, that's why we have a multilingual datasets section.

What do you think @nreimers?

Kind Regards,
Nandan Thakur

**Comment by thakur-nandan** [comment]
The README has been organized accordingly in the latest BEIR version v1.0.1. 
I am closing the issue.

Kind Regards,
Nandan Thakur
